package exceptions;
/**
 * Represents a self loop within the graph, which is not allowed
 * with simple graphs.
 *
 * DO NOT EDIT THIS FILE!
 *
 * @author Josh Archer
 * @version 1.0
 */
public class SelfLoopException extends RuntimeException
{
    /**
     * Creates a new exception with message.
     * @param message description of the error that occurred
     */
    public SelfLoopException(String message)
    {
        super(message);
    }
}
